# Generated by Django 4.1 on 2022-10-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fstp_pereval', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pereval',
            name='status',
            field=models.CharField(choices=[('NW', 'новый'), ('RJ', 'модерация прошла, информация не принята'), ('AC', 'модерация прошла успешно'), ('PD', 'принято на модерацию')], default='NW', max_length=2),
        ),
    ]
