# Generated by Django 4.1 on 2022-10-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fstp_pereval', '0002_alter_pereval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pereval',
            name='status',
            field=models.CharField(choices=[('AC', 'модерация прошла успешно'), ('NW', 'новый'), ('RJ', 'модерация прошла, информация не принята'), ('PD', 'принято на модерацию')], default='NW', max_length=2),
        ),
    ]
